apiVersion: graphdb.tigergraph.com/v1alpha1
kind: TigerGraph
metadata:
  name: tg-test-cluster
  namespace: tigergraph
spec:
  ha: 2
  image: docker.io/tigergraph/tigergraph-k8s:4.1.0
  imagePullPolicy: IfNotPresent
  imagePullSecrets:
  - name: tigergraph-image-pull-secret
  license: ${YOUR_LICENSE}
  listener:
    type: LoadBalancer
  privateKeyName: ssh-key-secret
  replicas: 4
  resources:
    requests:
      cpu: "6"
      memory: 12Gi
  storage:
    type: persistent-claim
    volumeClaimTemplate:
      resources:
        requests:
          storage: 100G
      storageClassName: standard
  regionAware:
    enable: true
    topologyKey: topology.kubernetes.io/zone
  topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule #ScheduleAnyway
        labelSelector:
          matchLabels:
            tigergraph.com/cluster-pod: tg-test-cluster
        matchLabelKeys:
          - pod-template-hash