apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: slack-config
  labels:
    alertmanager: config
spec:
  route:
    groupBy: ['alertname', 'job','severity']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 1m
    receiver: "slack-receiver"
    routes:
      - receiver: "slack-receiver"
        continue: true
  receivers:
    - name: "slack-receiver"
      slackConfigs:
        - sendResolved: true
          apiURL:
            name: slack-webhook-url
            key: webhook-url
          channel: "#operator-monitoring-test"
          color: '{{ if eq .Status "firing" }}danger{{ else }}good{{ end }}'
          text: |-
            {{ range .Alerts }}
              *Alert:* {{ .Annotations.summary }} - `{{ .Labels.severity }}`
              *Description:* {{ .Annotations.description }}
              *Details:*
              {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
              {{ end }}
            {{ end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: slack-webhook-url
type: Opaque
stringData:
  webhook-url: https://hooks.slack.com/services/YOUR_SLACK_WEBHOOK_URL